/* Regras comerciais: FREE = somente Caixa. PRO = sistema completo + relatórios. Não altera Supabase Auth. */
(function(){
 const paid=new URLSearchParams(location.search).get('modo')==='pago';
 function clean(){document.getElementById('svcDuracao')?.style?.setProperty('display','none');document.getElementById('svcDescricao')?.remove();document.querySelectorAll('#servicosList .service-row .muted').forEach(x=>x.textContent=x.textContent.split('·')[0].trim());const p=document.getElementById('agenda');if(p){p.querySelector('.agenda-toolbar')?.remove();document.getElementById('agendaList')?.remove();p.querySelector('.agenda-atendimento')?.remove();const t=p.querySelector('h2');if(t)t.textContent='Agendar contato';const s=p.querySelector('.topline .muted');if(s)s.textContent='Salve o contato do cliente para atendimento';}}
 function reports(){if(!document.getElementById('relatorios')&&!document.querySelector('nav .tab[data-tab="relatorios"]')){const n=document.querySelector('nav');if(n){const b=document.createElement('button');b.className='tab pro-only';b.dataset.tab='relatorios';b.textContent='Relatórios';n.appendChild(b);}const main=document.querySelector('main');if(main){const sec=document.createElement('section');sec.id='relatorios';sec.className='panel';sec.innerHTML='<div class="topline"><div><h2>Relatórios</h2><p class="muted">Resumo financeiro e de atendimentos</p></div><button id="gerarRelatorioBtn">Atualizar relatório</button></div><div class="stats"><div class="stat"><span>Faturamento</span><strong id="repFaturamento">R$ 0,00</strong></div><div class="stat"><span>Entradas</span><strong id="repEntradas">R$ 0,00</strong></div><div class="stat"><span>Saídas</span><strong id="repSaidas">R$ 0,00</strong></div><div class="stat"><span>Atendimentos</span><strong id="repAtendimentos">0</strong></div></div><div class="card table-card"><div class="section-title">Serviços realizados</div><div id="repServicos"></div></div><div class="card table-card"><div class="section-title">Movimentações</div><div id="repMovs"></div></div>';main.appendChild(sec);$("gerarRelatorioBtn")?.addEventListener('click',renderReport);}}
 function $(id){return document.getElementById(id)}
 function renderReport(){const mov=window.movimentacoes||[];const at=window.atendimentos||[];const ent=mov.filter(x=>x.tipo==='entrada').reduce((a,x)=>a+Number(x.valor||0),0);const sai=mov.filter(x=>x.tipo==='saida').reduce((a,x)=>a+Number(x.valor||0),0);if($('repFaturamento'))$('repFaturamento').textContent=(ent).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});if($('repEntradas'))$('repEntradas').textContent=ent.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});if($('repSaidas'))$('repSaidas').textContent=sai.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});if($('repAtendimentos'))$('repAtendimentos').textContent=at.length;const by={};at.forEach(x=>{const k=x.servico||'Outros';by[k]=(by[k]||0)+Number(x.valor||0);});if($('repServicos'))$('repServicos').innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="row"><b>${esc(k)}</b><strong>${v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong></div>`).join('')||'<div class="empty">Nenhum atendimento.</div>';if($('repMovs'))$('repMovs').innerHTML=mov.slice(0,100).map(x=>`<div class="row"><div><b>${esc(x.descricao||'Movimentação')}</b><div class="muted">${new Date(x.data_movimento).toLocaleString('pt-BR')}</div></div><strong>${x.tipo==='entrada'?'+':'-'} ${Number(x.valor||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong></div>`).join('')||'<div class="empty">Nenhuma movimentação.</div>';}
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
 function applyPlan(){reports();document.querySelectorAll('nav .tab').forEach(b=>{if(!paid&&b.dataset.tab!=='dashboard')b.style.display='none';else if(paid)b.style.display='';});if(!paid){document.querySelectorAll('main .panel').forEach(p=>{if(p.id!=='dashboard')p.classList.remove('active');});}document.querySelector('nav')?.addEventListener('click',e=>{const b=e.target.closest('.tab');if(!b)return;if(!paid&&b.dataset.tab!=='dashboard'){e.preventDefault();e.stopPropagation();return;}if(b.dataset.tab==='relatorios')setTimeout(renderReport,0);});}
 function after(){clean();applyPlan();setTimeout(clean,100);}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',after);else after();
 const r=window.renderServicos;if(typeof r==='function')window.renderServicos=function(){const z=r.apply(this,arguments);setTimeout(clean,0);return z;};
 if(!paid)return;
 window.PAID_MODE=true;
 const PLANS={mensal:{label:'Mensal',price:29.90},trimestral:{label:'Trimestral',price:79.90},semestral:{label:'Semestral',price:149.90},anual:{label:'Anual',price:249.90}};let selected=localStorage.getItem('bc_paid_plan')||'mensal';
 const client=()=>window.supabase.createClient('https://zjeclsozvjymuzwyhvqj.supabase.co','sb_publishable_WyjaTHvDUwGPCwHaXcdApw_xlssm0TE');
 const hide=()=>['authView','setupView','appView'].forEach(id=>$(id)?.classList.add('hidden'));const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 function styles(){if($('paidStyles'))return;const s=document.createElement('style');s.id='paidStyles';s.textContent='.paid-card{max-width:820px}.paid-plans{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.paid-plan{display:flex;flex-direction:column;gap:6px;min-height:125px;justify-content:center;align-items:center;border:2px solid #ddd;border-radius:14px;background:#fff;padding:14px;cursor:pointer}.paid-plan strong{font-size:22px}.paid-plan span{font-size:12px;color:#777}.paid-plan.selected{border-color:#111;box-shadow:0 0 0 2px #111 inset}@media(max-width:700px){.paid-plans{grid-template-columns:1fr 1fr}}';document.head.appendChild(s);}
 function mount(){if($('paidView'))return;styles();const el=document.createElement('div');el.id='paidView';el.className='center';el.innerHTML=`<div class="card auth-card wide-card paid-card"><div class="brand brand-center"><span class="brand-mark">✂</span><span>Barbearia Caixa PRO</span></div><h1>Escolha seu plano</h1><p class="muted">Acesso completo após a confirmação do pagamento pelo Asaas.</p><div class="paid-plans">${Object.entries(PLANS).map(([k,p])=>`<button class="paid-plan ${k===selected?'selected':''}" data-plan="${k}"><b>${p.label}</b><strong>${money(p.price)}</strong><span>assinatura recorrente</span></button>`).join('')}</div><button id="paidContinue">Continuar para pagamento</button><button id="paidBack" class="secondary">Usar versão grátis</button><div id="paidMsg" class="msg"></div></div>`;document.body.appendChild(el);el.querySelectorAll('.paid-plan').forEach(b=>b.onclick=()=>{selected=b.dataset.plan;localStorage.setItem('bc_paid_plan',selected);el.querySelectorAll('.paid-plan').forEach(x=>x.classList.toggle('selected',x===b));});$('paidContinue').onclick=startPayment;$('paidBack').onclick=()=>location.href=location.pathname;}
 const setMsg=t=>{if($('paidMsg'))$('paidMsg').textContent=t||''};
 async function startPayment(){const {data:{session}}=await client().auth.getSession();if(!session){hide();$('authView')?.classList.remove('hidden');return;}setMsg('Preparando pagamento no Asaas...');try{const r=await fetch('/api/create-subscription',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({plan:selected})});const j=await r.json();if(!r.ok)throw Error(j.error||'Não foi possível criar a assinatura.');if(j.checkout_url){location.href=j.checkout_url;return;}setMsg('Assinatura criada. Aguarde a primeira cobrança.');}catch(e){setMsg(e.message);}}
 window.ensurePaidAccess=async function(empresaId){try{const c=client();const {data:{session}}=await c.auth.getSession();if(!session){hide();$('authView')?.classList.remove('hidden');return false;}const {data:subs}=await c.from('assinaturas').select('*').eq('empresa_id',empresaId).order('created_at',{ascending:false}).limit(1);let sub=subs?.[0]||null;if(sub?.asaas_subscription_id&&sub.status!=='ativa'){try{await fetch('/api/check-subscription',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({assinatura_id:sub.id,asaas_subscription_id:sub.asaas_subscription_id})});const q=await c.from('assinaturas').select('*').eq('id',sub.id).maybeSingle();sub=q.data||sub;}catch(_e){}}const active=sub?.status==='ativa';if(active){$('paidView')?.remove();applyPlan();return true;}mount();hide();$('paidView')?.classList.remove('hidden');setMsg(sub?.status==='pendente'?'Pagamento pendente. Conclua a cobrança no Asaas e aguarde a confirmação automática.':'Escolha um plano para liberar o PRO.');return false;}catch(e){mount();hide();$('paidView')?.classList.remove('hidden');setMsg('Não foi possível verificar a assinatura.');return false;}};
 const old=window.loadProfile;if(typeof old==='function')window.loadProfile=async function(){const out=await old.apply(this,arguments);try{const c=client();const {data:{session}}=await c.auth.getSession();if(session){const {data:p}=await c.from('perfis').select('empresa_id').eq('id',session.user.id).maybeSingle();if(p?.empresa_id){const ok=await window.ensurePaidAccess(p.empresa_id);if(!ok)$('appView')?.classList.add('hidden');}}}catch(_e){}return out;};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mount();});else mount();
})();
